services:
  amqp-service:
    image: rabbitmq:4-management-alpine
    ports:
      - '${AMQP_PORT}:5672'
      - '${AMQP_DASHBOARD_PORT}:15672'
    networks:
      - snapnet

  clock-service:
    build:
      args:
        SERVICE: ${SERVICE_CLOCK_SERVICE}
    extends:
      file: docker-base.yml
      service: base-service

  mail-service:
    build:
      args:
        SERVICE: ${SERVICE_MAIL_SERVICE}
    extends:
      file: docker-base.yml
      service: base-service

  read-service:
    build:
      args:
        SERVICE: ${SERVICE_READ_SERVICE}
    extends:
      file: docker-base.yml
      service: base-service
    ports:
      - '${READ_SERVICE_PORT}:3000'

  score-service:
    build:
      args:
        SERVICE: ${SERVICE_SCORE_SERVICE}
    extends:
      file: docker-base.yml
      service: base-service

  submission-service:
    build:
      args:
        SERVICE: ${SERVICE_SUBMISSION_SERVICE}
    extends:
      file: docker-base.yml
      service: base-service

  target-service:
    build:
      args:
        SERVICE: ${SERVICE_TARGET_SERVICE}
    extends:
      file: docker-base.yml
      service: base-service

networks:
  snapnet:
    driver: bridge
