services:
  base-service:
    build:
      context: .
    depends_on:
      - mysql-service
      - kafka-service
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=http://mysql-service
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_ROOT_USER}
    networks:
      - snapnet
