CREATE DATABASE IF NOT EXISTS clock_db;
CREATE DATABASE IF NOT EXISTS mail_db;
CREATE DATABASE IF NOT EXISTS read_db;
CREATE DATABASE IF NOT EXISTS score_db;
CREATE DATABASE IF NOT EXISTS submission_db;
CREATE DATABASE IF NOT EXISTS target_db;
CREATE DATABASE IF NOT EXISTS auth_db;
